# Ví dụ về KNN với bộ dữ liệu hoa Iris
Bộ dữ liệu này bao gồm thông tin của ba loại hoa Iris (một loài hoa lan) khác nhau: Iris setosa, Iris virginica và Iris versicolor. Mỗi loại có 50 bông hoa được đo với dữ liệu là 4 thông tin: chiều dài, chiều rộng đài hoa (sepal), và chiều dài, chiều rộng cánh hoa (petal). (Chú ý, đây không phải là bộ cơ sở dữ liệu ảnh như MNIST, mỗi điểm dữ liệu trong tập này chỉ là một vector 4 chiều).

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

### Load dữ liệu


In [ ]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

print('number of classes:', len(np.unique(iris_y)))
print('number of data points:', len(iris_y))

X0 = iris_X[iris_y == 0]
print('\n Sample of class 0:\n', X0[:5])

X1 = iris_X[iris_y == 1]
print('\n Sample of class 1:\n', X1[:5])    

X2 = iris_X[iris_y == 2]
print('\n Sample of class 2:\n', X2[:5])

number of classes: 3
number of data points: 150

 Sample of class 0:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Tách training và test sets
Giả sử chúng ta muốn dùng 50 điểm dữ liệu cho test set, 100 điểm còn lại cho training set. Scikit-learn có một hàm số cho phép chúng ta ngẫu nhiên lựa chọn các điểm này.

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_X, iris_y, test_size=50, random_state = 17)

print('Train set size:', len(y_train))
print('Test set size:', len(y_test))

Train set size: 100
Test set size: 50


In [10]:
clf = neighbors.KNeighborsClassifier(n_neighbors=1, weights='uniform', algorithm='auto')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print('Print results for the first 20 test points:')
print('Predicted:', y_pred[20:40])
print('Actual:   ', y_test[20:40])

Print results for the first 20 test points:
Predicted: [1 0 2 1 1 1 1 1 0 1 0 1 0 0 1 1 1 2 1 0]
Actual:    [2 0 2 1 1 1 1 1 0 1 0 1 0 0 1 1 1 2 1 0]


### Đánh giá

In [13]:
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f %%' %(100*accuracy_score(y_test, y_pred)))

Accuracy: 96.00 %


Có thể đổi số lượng neighbors, weights ở thuật toán và đưa ra các kết quả đánh giá khác